# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageImgur' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SDWebImage', '~> 5.0'
  # Pods for ImageImgur

  target 'ImageImgurTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImageImgurUITests' do
    # Pods for testing
  end

end
